// <auto-generated />
using System;
using Thekdar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Thekdar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405102501_InitialIntSchema")]
    partial class InitialIntSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DailyRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Hourly rate in dollars");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Employee's email address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Employee's first name");

                    b.Property<DateTime>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Date employee was hired");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Whether employee is available for work");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag - true means employee is deactivated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Employee's last name");

                    b.Property<string>("PanCardImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Path to PAN card image file");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("PAN number - optional");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Primary phone number - exactly 10 digits");

                    b.Property<string>("Phone2")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Secondary phone number - optional, exactly 10 digits if provided");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Path to employee profile picture");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Employee's trade/specialization (Electrician, Plumber, etc.)");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("IX_Employees_ContractorId");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Employees_IsAvailable");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Employees_IsDeleted");

                    b.HasIndex("Trade")
                        .HasDatabaseName("IX_Employees_Trade");

                    b.HasIndex("ContractorId", "IsAvailable", "IsDeleted")
                        .HasDatabaseName("IX_Employees_Contractor_Available_Deleted");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Thekdar.Models.JobAssignmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("When the assignment record was created");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("When the employee was assigned");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When work ended (optional)");

                    b.Property<decimal>("HoursWorked")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Total hours worked on this job");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Assistant")
                        .HasComment("Role: Lead, Assistant, Apprentice");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When work started (optional)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Assigned")
                        .HasComment("Status: Assigned, Working, Completed");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("IX_JobAssignments_AssignedByUserId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_JobAssignments_EmployeeId");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_JobAssignments_JobId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_JobAssignments_Status");

                    b.HasIndex("JobId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobAssignments_JobId_EmployeeId_Unique");

                    b.ToTable("JobAssignments", (string)null);
                });

            modelBuilder.Entity("Thekdar.Models.JobModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Job site address");

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Client/customer name");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Job creation timestamp (UTC)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Detailed job description");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Scheduled date for the job (UTC)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasComment("Job status: Active, PendingConfirmation, or Completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Job title/summary");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId")
                        .HasDatabaseName("IX_Jobs_CompletedByUserId");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Jobs_CreatedByUserId");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_Jobs_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Thekdar.Models.PayrollModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseWage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BonusReason")
                        .HasColumnType("text");

                    b.Property<int>("ContractorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("integer");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeductionReason")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OvertimeMultiplier")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OvertimeWage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<bool>("PayslipGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("PayslipNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalWage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayslipNumber")
                        .IsUnique();

                    b.HasIndex("PeriodEnd");

                    b.HasIndex("PeriodStart");

                    b.HasIndex("Status");

                    b.ToTable("Payrolls", (string)null);
                });

            modelBuilder.Entity("Thekdar.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasComment("User's age - must be between 18-100");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Account creation timestamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User's email address - must be unique");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last login timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User's full name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("BCrypt hashed password");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Password reset token");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("Phone number - exactly 10 digits");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("bytea")
                        .HasComment("Profile picture as byte array");

                    b.Property<string>("ProfilePictureContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("MIME type of profile picture (image/jpeg, image/png, etc.)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Password reset token expiration");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasComment("User role: Admin or Contractor");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Account status: Active or Inactive");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EmployeeModel", b =>
                {
                    b.HasOne("Thekdar.Models.UserModel", "Contractor")
                        .WithMany("Employees")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Employees_ContractorId");

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("Thekdar.Models.JobAssignmentModel", b =>
                {
                    b.HasOne("Thekdar.Models.UserModel", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_JobAssignments_AssignedByUserId");

                    b.HasOne("EmployeeModel", "Employee")
                        .WithMany("JobAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_JobAssignments_EmployeeId");

                    b.HasOne("Thekdar.Models.JobModel", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JobAssignments_JobId");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Employee");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Thekdar.Models.JobModel", b =>
                {
                    b.HasOne("Thekdar.Models.UserModel", "CompletedBy")
                        .WithMany("JobsCompleted")
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Jobs_CompletedByUserId");

                    b.HasOne("Thekdar.Models.UserModel", "CreatedBy")
                        .WithMany("JobsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Jobs_CreatedByUserId");

                    b.Navigation("CompletedBy");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Thekdar.Models.PayrollModel", b =>
                {
                    b.HasOne("Thekdar.Models.UserModel", "Contractor")
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeModel", b =>
                {
                    b.Navigation("JobAssignments");
                });

            modelBuilder.Entity("Thekdar.Models.UserModel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("JobsCompleted");

                    b.Navigation("JobsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
